name: CI/CD for NestJS Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker build --target production -t ${{ vars.SERVICE_NAME }}:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag ${{ vars.SERVICE_NAME }}:latest ${{ secrets.DOCKER_USERNAME }}/${{ vars.SERVICE_NAME }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ vars.SERVICE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        env:
          HOST: ${{ secrets.VM_HOST }}
          USER: ${{ secrets.VM_USER }}
          ENV_PATH: ${{ secrets.ENV_PATH }}
          SERVICE_NAME: ${{ vars.SERVICE_NAME }}
          SERVICE_PORT: ${{ vars.SERVICE_PORT }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            sudo docker pull $DOCKER_USERNAME/${SERVICE_NAME}:latest

            sudo docker stop $SERVICE_NAME || true
            sudo docker rm $SERVICE_NAME || true
            sudo docker system prune -f

            sudo docker run -d --name $SERVICE_NAME \
              --env-file $ENV_PATH \
              -p $SERVICE_PORT:$SERVICE_PORT $DOCKER_USERNAME/${SERVICE_NAME}:latest
          EOF
